// Code generated by goa v2.0.0-wip, DO NOT EDIT.
//
// Incident views
//
// Command:
// $ goa gen github.com/rightscale/governance/front_service/design

package views

import (
	goa "goa.design/goa"
)

// Incident is the viewed result type that is projected based on a view.
type Incident struct {
	// Type to project
	Projected *IncidentView
	// View to render
	View string
}

// IncidentList is the viewed result type that is projected based on a view.
type IncidentList struct {
	// Type to project
	Projected *IncidentListView
	// View to render
	View string
}

// Escalations is the viewed result type that is projected based on a view.
type Escalations struct {
	// Type to project
	Projected *EscalationsView
	// View to render
	View string
}

// Resolutions is the viewed result type that is projected based on a view.
type Resolutions struct {
	// Type to project
	Projected *ResolutionsView
	// View to render
	View string
}

// IncidentView is a type that runs validations on a projected type.
type IncidentView struct {
	// id is the ID of the incident, must be unique in the project.
	ID *string
	// Project represents a RightScale project and provides some information about
	// the project.
	Project *ProjectView
	// href is the href of the incident.
	Href *string
	// applied_policy links to key attributes of the applied policy that initiated
	// the incident.
	AppliedPolicy *AppliedPolicyView
	// summary is a summary of the incident.
	Summary *string
	// message is a description of the incident.
	Detail *string
	// data is the data about the resources that violate the policy.
	Data *interface{}
	// The number of items in violation data.
	ViolationDataCount *uint
	// created_at is the incident creation timestamp in RFC3339 format.
	CreatedAt *string
	// updated_at is the incident update timestamp in RFC3339 format.
	UpdatedAt *string
	// resolved_at is the incident resolution timestamp in RFC3339 format.
	ResolvedAt *string
	// resolved_by is the RightScale user that resolved the incident if it was
	// resolved manually.
	ResolvedBy *UserView
	// resolution_message is an optional explaination of why the incident is
	// resolved.
	ResolutionMessage *string
	// state represents the current handling status of the incident.
	State *string
	// severity defines the severity level of the incident.
	Severity *string
	// category is the type categorization of the incident.
	Category *string
	// options lists the configuration options used to parameterize the policy that
	// created the incident.
	Options []*ConfigurationOptionView
	// dry_run is a flag used for testing a policy, that determines whether this
	// incident should trigger escalation actions.
	DryRun *bool
	// action_failed indicates whether any of the incident's actions failed during
	// execution.
	ActionFailed *bool
	// kind is "gov#incident".
	Kind *string
	// etag is an HTTP ETag for the incident.
	Etag *string
	// not_modified is a flag used internally that indicates how to encode the HTTP
	// response (i.e. 200 or 304).
	NotModified *string
}

// ProjectView is a type that runs validations on a projected type.
type ProjectView struct {
	// id is the Project ID
	ID *uint
	// name is the Project Name
	Name *string
	// org_id is the RightScale Organization ID
	OrgID *uint
	// org_name is the RightScale Organization Name
	OrgName *string
}

// AppliedPolicyView is a type that runs validations on a projected type.
type AppliedPolicyView struct {
	// id identifies an applied policy by ID.
	ID *string
	// name provides a name for this specific application of the policy.
	Name *string
	// Project represents a RightScale project and provides some information about
	// the project.
	Project *ProjectView
	// href is the href of the applied policy.
	Href *string
	// policy_template links to key attributes of the policy template from which
	// the applied policy originated.
	PolicyTemplate *PolicyTemplateView
	// published_template links to key attributes of the published template from
	// which the applied policy originated.
	PublishedTemplate *PublishedTemplateView
	// description provides a human readable description for this specific
	// application of the policy.
	Description *string
	// doc_link is a HTTP URI to a page containing detailed documentation for the
	// policy.
	DocLink *string
	// info is an arbitrary set of key/value pairs that provide additional
	// information such as the policy author, support contact information, etc.
	Info map[string]string
	// created_by is the RightScale user that applied the policy.
	CreatedBy *UserView
	// created_at is the applied policy creation timestamp in RFC3339 format.
	CreatedAt *string
	// updated_at is the applied policy update timestamp in RFC3339 format.
	UpdatedAt *string
	// severity defines the severity level of incidents raised from this applied
	// policy.
	Severity *string
	// category is the type categorization of the applied policy.
	Category *string
	// frequency specifies the frequency with which to run policy evaluations
	Frequency *string
	// dry_run is a flag used for testing a policy so that an incident can be
	// raised without performing an action.
	DryRun *bool
	// options lists the configuration options used to parameterize the policy.
	Options []*ConfigurationOptionView
	// status is used to identify the current status of the applied policy.
	Status *string
	// error is the error message returned if the evaluation failed. On success
	// this attribute is empty.
	Error *string
	// errored_at is the applied policy error timestamp in RFC3339 format. On
	// success this attribute is empty.
	ErroredAt *string
	// kind is "gov#applied_policy".
	Kind *string
}

// PolicyTemplateView is a type that runs validations on a projected type.
type PolicyTemplateView struct {
	// id identifies a policy template by ID.
	ID *string
	// name is the unique name of the policy template in the project.
	Name *string
	// project_id is the ID of the project that the policy template applies to.
	ProjectID *uint
	// rs_pt_ver is the policy engine version.
	RsPtVer *uint
	// short_description is the short description of the policy template.
	ShortDescription *string
	// long_description is the long description of the policy template. The content
	// can be markdown.
	LongDescription *string
	// doc_link is an HTTP URI to a page containing detailed documentation for the
	// policy.
	DocLink *string
	// info is an arbitrary set of key/value pairs that provide additional
	// information such as the policy author, support contact information, etc.
	Info map[string]string
	// href is the href of the policy template.
	Href *string
	// filename is the name of the file that was uploaded to create the policy
	// template.
	Filename *string
	// source is the policy template source code.
	Source *string
	// fingerprint is a SHA created during compilation. It is used to determine if
	// the template is outdated.
	Fingerprint *string
	// category is the type categorization of the policy template.
	Category *string
	// created_by is the RightScale user that created the policy template.
	CreatedBy *UserView
	// created_at is the policy template creation timestamp in RFC3339 format.
	CreatedAt *string
	// updated_by is the RightScale user that updated the policy template.
	UpdatedBy *UserView
	// updated_at is the last update timestamp in RFC3339 format.
	UpdatedAt *string
	// permissions is a list of permissions required to run the policy.
	Permissions map[string]*PermissionView
	// required_roles is a list of governance roles, derived from permissions,
	// required to run the policy.
	RequiredRoles []string
	// parameters is a list of parameters required to apply the policy.
	Parameters map[string]*ParameterView
	// severity defines the severity level of incidents raised from this policy
	// template.
	Severity *string
	// kind is "gov#policy_template".
	Kind *string
}

// UserView is a type that runs validations on a projected type.
type UserView struct {
	// ID of user
	ID *uint
	// email of user
	Email *string
	// name of user, usually of the form 'First Last'
	Name *string
}

// PermissionView is a type that runs validations on a projected type.
type PermissionView struct {
	// Name of a permission
	Name *string `json:"name"`
	// Label is used in the UI
	Label *string `json:"label"`
	// List of resource names the permission is applied to
	Resources []string `json:"resources"`
	// List of action names the permission is applied to
	Actions []string `json:"actions"`
}

// ParameterView is a type that runs validations on a projected type.
type ParameterView struct {
	// Name of the parameter
	Name *string `json:"name"`
	// Type of the parameter
	Type *string `json:"type"`
	// Label to show in the UI
	Label *string `json:"label"`
	// The index of this parameter in the list
	Index *uint `json:"index"`
	// The category used to group parameters
	Category *string `json:"category"`
	// Description of the parameter
	Description *string `json:"description"`
	// The default value for the parameter
	Default *interface{} `json:"default"`
	// no_echo determines whether the value of the parameter should be hidden in
	// UIs and API responses.
	NoEcho *bool `json:"no_echo"`
	// List of values allowed for this parameter
	AllowedValues []interface{} `json:"allowed_values"`
	// The minimum length of a string parameter
	MinLength *uint `json:"min_length"`
	// The maximum length of a string parameter
	MaxLength *uint `json:"max_length"`
	// The minimum value of a number parmameter
	MinValue *float64 `json:"min_value"`
	// The maximum value of a number parameter
	MaxValue *float64 `json:"max_value"`
	// The regular expression pattern used to validate a string parameter
	AllowedPattern *RegexpView `json:"allowed_pattern"`
	// The description used for constraints
	ConstraintDescription *string `json:"constraint_description"`
}

// RegexpView is a type that runs validations on a projected type.
type RegexpView struct {
	// Pattern is the regular expression pattern.
	Pattern *string `json:"pattern"`
	// Options are the regular expression options. Options i (case insensitve) and
	// m (match over newlines) supported.
	Options *string `json:"options"`
}

// PublishedTemplateView is a type that runs validations on a projected type.
type PublishedTemplateView struct {
	// id identifies a published template by ID.
	ID *string
	// name is the unique name of the published template in the organization.
	Name *string
	// org_id is the ID of the organization that the published template belongs to.
	OrgID *uint
	// project_id is the ID of the project that the published template is published
	// from.
	ProjectID *uint
	// policy_template_id is the ID of the policy template from which the published
	// template originated.
	PolicyTemplateID *string
	// policy_template_url is the full URL to the policy template from which the
	// published template originated.
	PolicyTemplateURL *string
	// policy_template_fingerprint is fingerprint of the policy template. It is
	// used to determine if the policy template that this was published from is
	// outdated.
	PolicyTemplateFingerprint *string
	// rs_pt_ver is the policy engine version.
	RsPtVer *uint
	// short_description is the short description of the published template.
	ShortDescription *string
	// long_description is the long description of the published template. The
	// content can be markdown.
	LongDescription *string
	// doc_link is a HTTP URI to a page containing detailed documentation for the
	// policy.
	DocLink *string
	// info is an arbitrary set of key/value pairs that provide additional
	// information such as the policy author, support contact information, etc.
	Info map[string]string
	// href is the self-referential href of the published template.
	Href *string
	// filename is the name of the file that was uploaded to create the policy
	// template.
	Filename *string
	// source is published template source code.
	Source *string
	// fingerprint is a SHA created during compilation. It is used to determine if
	// the policy template that this was published from is outdated.
	Fingerprint *string
	// category is the type categorization of the published template.
	Category *string
	// created_by is the RightScale user that created the published template.
	CreatedBy *UserView
	// created_at is the published template creation timestamp in RFC3339 format.
	CreatedAt *string
	// updated_by is the RightScale user that updated the published template.
	UpdatedBy *UserView
	// updated_at is the published template update timestamp in RFC3339 format.
	UpdatedAt *string
	// permissions is a list of permissions required to run the policy.
	Permissions map[string]*PermissionView
	// required_roles is a list of governance roles, derived from permissions,
	// required to run the policy.
	RequiredRoles []string
	// parameters is a list of parameters required to apply the policy.
	Parameters map[string]*ParameterView
	// severity defines the severity level of incidents raised from this published
	// template.
	Severity *string
	// built_in is a flag to indicate whether the published template is a
	// "built-in" RS-supplied template.
	BuiltIn *bool
	// hidden is a flag to indicate whether the published template is hidden.
	Hidden *bool
	// hidden_by is the RightScale user that marked the published template as
	// hidden.
	HiddenBy *UserView
	// hidden_at is the hidden at timestamp in RFC3339 format.
	HiddenAt *string
	// kind is "gov#published_template".
	Kind *string
}

// ConfigurationOptionView is a type that runs validations on a projected type.
type ConfigurationOptionView struct {
	// name of option
	Name *string
	// label of option
	Label *string
	// type of option
	Type *string
	// value of option
	Value *interface{}
}

// IncidentListView is a type that runs validations on a projected type.
type IncidentListView struct {
	// count is the number of incidents in the list.
	Count *uint
	// etag is an HTTP ETag for the incident list.
	Etag *string
	// items is the array of incidents.
	Items IncidentCollectionView
	// not_modified is a flag used internally that indicates how to encode the HTTP
	// response (i.e. 200 or 304).
	NotModified *string
	// kind is "gov#incident_list".
	Kind *string
}

// IncidentCollectionView is a type that runs validations on a projected type.
type IncidentCollectionView []*IncidentView

// EscalationsView is a type that runs validations on a projected type.
type EscalationsView struct {
	// status is the status of all of the escalations.
	Status *string
	// escalations is the set of escalations.
	Escalations []*EscalationView
	// started_at is the time when the incident handling is started.
	StartedAt *string
	// finished_at is the time when the incident handling is finished. It exists
	// when the status is completed or failed.
	FinishedAt *string
}

// EscalationView is a type that runs validations on a projected type.
type EscalationView struct {
	// status is the status of the set of escalation actions.
	Status *string
	// name is the name of the escalation.
	Name *string
	// actions is the list of individual actions.
	Actions []*EscalationActionView
}

// EscalationActionView is a type that runs validations on a projected type.
type EscalationActionView struct {
	// type is the type of the action.
	Type *string
	// status is the status of the action.
	Status *string
	// started_at is the time when the action was started.
	StartedAt *string
	// finished_at is the time when the action was finished.
	FinishedAt *string
	// error is any error occurred when handling the action.
	Error *string
	// approval_request is the approval request resource (if the type is
	// request_approval).
	ApprovalRequest *ApprovalRequestView
	// process_href is the href of a cloud workflow process. Required if the type
	// is cloud_workflow.
	ProcessHref *string
}

// ApprovalRequestView is a type that runs validations on a projected type.
type ApprovalRequestView struct {
	// id identifies an approval request by ID.
	ID *string
	// project_id is the ID of the project where this approval request is created.
	ProjectID *uint
	// href is the href of the approval request
	Href *string
	// label is a short title for this approval request
	Label *string
	// description describes the details for this approval request.
	Description *string
	// subject is the subject of the approval.
	Subject *ApprovalSubject2
	// created_at is the approval request creation timestamp in RFC3339 format.
	CreatedAt *string
	// updated_at is the last update timestamp in RFC3339 format.
	UpdatedAt *string
	// parameters is a list of parameters required for approval request.
	Parameters map[string]*ParameterView
	// status is the status of this approval request.
	Status *string
	// options lists the configuration options used to parameterize the approval
	// request.
	Options []*ConfigurationOptionView
	// approved_by is the RightScale user that approved this approval request.
	ApprovedBy *UserView
	// approved_at is the approval timestamp in RFC3339 format.
	ApprovedAt *string
	// denial_comment is a comment that explains the reason for denial, if relevant.
	DenialComment *string
	// denied_by is the RightScale user that denied this approval request.
	DeniedBy *UserView
	// denied_at is the denial timestamp in RFC3339 format.
	DeniedAt *string
	// kind is "gov#approval_request".
	Kind *string
}

// ApprovalSubject2 is a type that runs validations on a projected type.
type ApprovalSubject2 struct {
	// kind is the kind of subject
	Kind *string
	// href is the href of the subject.
	Href *string
}

// ResolutionsView is a type that runs validations on a projected type.
type ResolutionsView struct {
	// status is the status of all of the resolutions.
	Status *string
	// resolutions is the set of resolutions.
	Resolutions []*ResolutionView
	// started_at is the time when the incident handling is started.
	StartedAt *string
	// finished_at is the time when the incident handling is finished. It exists
	// when the status is completed or failed.
	FinishedAt *string
}

// ResolutionView is a type that runs validations on a projected type.
type ResolutionView struct {
	// status is the status of the set of resolution actions.
	Status *string
	// name is the name of the resolution.
	Name *string
	// actions is the list of individual actions.
	Actions []*ResolutionActionView
}

// ResolutionActionView is a type that runs validations on a projected type.
type ResolutionActionView struct {
	// type is the type of the action.
	Type *string
	// status is the status of the action.
	Status *string
	// started_at is the time when the action was started.
	StartedAt *string
	// finished_at is the time when the action was finished.
	FinishedAt *string
	// error is any error occurred when handling the action.
	Error *string
	// approval_request is the approval request resource (if the type is
	// request_approval).
	ApprovalRequest *ApprovalRequestView
	// process_href is the href of a cloud workflow process. Required if the type
	// is cloud_workflow.
	ProcessHref *string
}

// Validate runs the validations defined on the viewed result type Incident.
func (result *Incident) Validate() (err error) {
	switch result.View {
	case "default", "":
		err = result.Projected.Validate()
	case "extended":
		err = result.Projected.ValidateExtended()
	case "source":
		err = result.Projected.ValidateSource()
	default:
		err = goa.InvalidEnumValueError("view", result.View, []interface{}{"default", "extended", "source"})
	}
	return
}

// Validate runs the validations defined on the viewed result type IncidentList.
func (result *IncidentList) Validate() (err error) {
	switch result.View {
	case "default", "":
		err = result.Projected.Validate()
	case "extended":
		err = result.Projected.ValidateExtended()
	default:
		err = goa.InvalidEnumValueError("view", result.View, []interface{}{"default", "extended"})
	}
	return
}

// Validate runs the validations defined on the viewed result type Escalations.
func (result *Escalations) Validate() (err error) {
	switch result.View {
	case "default", "":
		err = result.Projected.Validate()
	default:
		err = goa.InvalidEnumValueError("view", result.View, []interface{}{"default"})
	}
	return
}

// Validate runs the validations defined on the viewed result type Resolutions.
func (result *Resolutions) Validate() (err error) {
	switch result.View {
	case "default", "":
		err = result.Projected.Validate()
	default:
		err = goa.InvalidEnumValueError("view", result.View, []interface{}{"default"})
	}
	return
}

// Validate runs the validations defined on IncidentView using the "default"
// view.
func (result *IncidentView) Validate() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.Etag == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("etag", "result"))
	}
	if result.Project != nil {
		if err2 := result.Project.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/projects/[0-9]+/incidents/[0-9a-f]+$"))
	}
	if result.CreatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.created_at", *result.CreatedAt, goa.FormatDateTime))
	}
	if result.UpdatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.updated_at", *result.UpdatedAt, goa.FormatDateTime))
	}
	if result.ResolvedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.resolved_at", *result.ResolvedAt, goa.FormatDateTime))
	}
	if result.ResolvedBy != nil {
		if err2 := result.ResolvedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.State != nil {
		if !(*result.State == "triggered" || *result.State == "resolved" || *result.State == "terminated") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.state", *result.State, []interface{}{"triggered", "resolved", "terminated"}))
		}
	}
	if result.Severity != nil {
		if !(*result.Severity == "low" || *result.Severity == "medium" || *result.Severity == "high" || *result.Severity == "critical") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.severity", *result.Severity, []interface{}{"low", "medium", "high", "critical"}))
		}
	}
	for _, e := range result.Options {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#incident") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#incident"}))
		}
	}
	if result.NotModified != nil {
		if !(*result.NotModified == "true" || *result.NotModified == "false") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.not_modified", *result.NotModified, []interface{}{"true", "false"}))
		}
	}
	if result.AppliedPolicy != nil {
		if err2 := result.AppliedPolicy.ValidateLink(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// ValidateExtended runs the validations defined on IncidentView using the
// "extended" view.
func (result *IncidentView) ValidateExtended() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.Etag == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("etag", "result"))
	}
	if result.Project != nil {
		if err2 := result.Project.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/projects/[0-9]+/incidents/[0-9a-f]+$"))
	}
	if result.CreatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.created_at", *result.CreatedAt, goa.FormatDateTime))
	}
	if result.UpdatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.updated_at", *result.UpdatedAt, goa.FormatDateTime))
	}
	if result.ResolvedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.resolved_at", *result.ResolvedAt, goa.FormatDateTime))
	}
	if result.ResolvedBy != nil {
		if err2 := result.ResolvedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.State != nil {
		if !(*result.State == "triggered" || *result.State == "resolved" || *result.State == "terminated") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.state", *result.State, []interface{}{"triggered", "resolved", "terminated"}))
		}
	}
	if result.Severity != nil {
		if !(*result.Severity == "low" || *result.Severity == "medium" || *result.Severity == "high" || *result.Severity == "critical") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.severity", *result.Severity, []interface{}{"low", "medium", "high", "critical"}))
		}
	}
	for _, e := range result.Options {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#incident") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#incident"}))
		}
	}
	if result.NotModified != nil {
		if !(*result.NotModified == "true" || *result.NotModified == "false") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.not_modified", *result.NotModified, []interface{}{"true", "false"}))
		}
	}
	if result.AppliedPolicy != nil {
		if err2 := result.AppliedPolicy.ValidateLink(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// ValidateSource runs the validations defined on IncidentView using the
// "source" view.
func (result *IncidentView) ValidateSource() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.Etag == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("etag", "result"))
	}
	if result.Project != nil {
		if err2 := result.Project.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/projects/[0-9]+/incidents/[0-9a-f]+$"))
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#incident") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#incident"}))
		}
	}
	if result.NotModified != nil {
		if !(*result.NotModified == "true" || *result.NotModified == "false") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.not_modified", *result.NotModified, []interface{}{"true", "false"}))
		}
	}
	if result.AppliedPolicy != nil {
		if err2 := result.AppliedPolicy.ValidateSource(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// Validate runs the validations defined on ProjectView.
func (result *ProjectView) Validate() (err error) {

	return
}

// Validate runs the validations defined on AppliedPolicyView using the
// "default" view.
func (result *AppliedPolicyView) Validate() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Name == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("name", "result"))
	}
	if result.Href == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("href", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.Project != nil {
		if err2 := result.Project.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/projects/[0-9]+/applied_policies/[0-9a-f]+$"))
	}
	if result.DocLink != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.doc_link", *result.DocLink, goa.FormatURI))
	}
	if result.CreatedBy != nil {
		if err2 := result.CreatedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.CreatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.created_at", *result.CreatedAt, goa.FormatDateTime))
	}
	if result.UpdatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.updated_at", *result.UpdatedAt, goa.FormatDateTime))
	}
	if result.Severity != nil {
		if !(*result.Severity == "low" || *result.Severity == "medium" || *result.Severity == "high" || *result.Severity == "critical") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.severity", *result.Severity, []interface{}{"low", "medium", "high", "critical"}))
		}
	}
	if result.Frequency != nil {
		if !(*result.Frequency == "15 minutes" || *result.Frequency == "hourly" || *result.Frequency == "daily" || *result.Frequency == "weekly") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.frequency", *result.Frequency, []interface{}{"15 minutes", "hourly", "daily", "weekly"}))
		}
	}
	for _, e := range result.Options {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	if result.Status != nil {
		if !(*result.Status == "active" || *result.Status == "error") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.status", *result.Status, []interface{}{"active", "error"}))
		}
	}
	if result.ErroredAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.errored_at", *result.ErroredAt, goa.FormatDateTime))
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#applied_policy") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#applied_policy"}))
		}
	}
	if result.PolicyTemplate != nil {
		if err2 := result.PolicyTemplate.ValidateLink(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.PublishedTemplate != nil {
		if err2 := result.PublishedTemplate.ValidateLink(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// ValidateSource runs the validations defined on AppliedPolicyView using the
// "source" view.
func (result *AppliedPolicyView) ValidateSource() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Name == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("name", "result"))
	}
	if result.Href == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("href", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.Project != nil {
		if err2 := result.Project.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/projects/[0-9]+/applied_policies/[0-9a-f]+$"))
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#applied_policy") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#applied_policy"}))
		}
	}
	if result.PolicyTemplate != nil {
		if err2 := result.PolicyTemplate.ValidateSource(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.PublishedTemplate != nil {
		if err2 := result.PublishedTemplate.ValidateSource(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// ValidateLink runs the validations defined on AppliedPolicyView using the
// "link" view.
func (result *AppliedPolicyView) ValidateLink() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Name == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("name", "result"))
	}
	if result.Href == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("href", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/projects/[0-9]+/applied_policies/[0-9a-f]+$"))
	}
	if result.CreatedBy != nil {
		if err2 := result.CreatedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.CreatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.created_at", *result.CreatedAt, goa.FormatDateTime))
	}
	if result.Frequency != nil {
		if !(*result.Frequency == "15 minutes" || *result.Frequency == "hourly" || *result.Frequency == "daily" || *result.Frequency == "weekly") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.frequency", *result.Frequency, []interface{}{"15 minutes", "hourly", "daily", "weekly"}))
		}
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#applied_policy") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#applied_policy"}))
		}
	}
	if result.PolicyTemplate != nil {
		if err2 := result.PolicyTemplate.ValidateLink(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.PublishedTemplate != nil {
		if err2 := result.PublishedTemplate.ValidateLink(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// Validate runs the validations defined on PolicyTemplateView using the
// "default" view.
func (result *PolicyTemplateView) Validate() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Name == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("name", "result"))
	}
	if result.Href == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("href", "result"))
	}
	if result.Fingerprint == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("fingerprint", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.DocLink != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.doc_link", *result.DocLink, goa.FormatURI))
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/projects/[0-9]+/policy_templates/[0-9a-f]+$"))
	}
	if result.CreatedBy != nil {
		if err2 := result.CreatedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.CreatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.created_at", *result.CreatedAt, goa.FormatDateTime))
	}
	if result.UpdatedBy != nil {
		if err2 := result.UpdatedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.UpdatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.updated_at", *result.UpdatedAt, goa.FormatDateTime))
	}
	if result.Severity != nil {
		if !(*result.Severity == "low" || *result.Severity == "medium" || *result.Severity == "high" || *result.Severity == "critical") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.severity", *result.Severity, []interface{}{"low", "medium", "high", "critical"}))
		}
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#policy_template") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#policy_template"}))
		}
	}
	return
}

// ValidateExtended runs the validations defined on PolicyTemplateView using
// the "extended" view.
func (result *PolicyTemplateView) ValidateExtended() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Name == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("name", "result"))
	}
	if result.Href == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("href", "result"))
	}
	if result.Fingerprint == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("fingerprint", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.DocLink != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.doc_link", *result.DocLink, goa.FormatURI))
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/projects/[0-9]+/policy_templates/[0-9a-f]+$"))
	}
	if result.CreatedBy != nil {
		if err2 := result.CreatedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.CreatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.created_at", *result.CreatedAt, goa.FormatDateTime))
	}
	if result.UpdatedBy != nil {
		if err2 := result.UpdatedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.UpdatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.updated_at", *result.UpdatedAt, goa.FormatDateTime))
	}
	for _, v := range result.Parameters {
		if v != nil {
			if err2 := v.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	if result.Severity != nil {
		if !(*result.Severity == "low" || *result.Severity == "medium" || *result.Severity == "high" || *result.Severity == "critical") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.severity", *result.Severity, []interface{}{"low", "medium", "high", "critical"}))
		}
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#policy_template") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#policy_template"}))
		}
	}
	return
}

// ValidateSource runs the validations defined on PolicyTemplateView using the
// "source" view.
func (result *PolicyTemplateView) ValidateSource() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Name == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("name", "result"))
	}
	if result.Href == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("href", "result"))
	}
	if result.Fingerprint == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("fingerprint", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/projects/[0-9]+/policy_templates/[0-9a-f]+$"))
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#policy_template") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#policy_template"}))
		}
	}
	return
}

// ValidateLink runs the validations defined on PolicyTemplateView using the
// "link" view.
func (result *PolicyTemplateView) ValidateLink() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Name == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("name", "result"))
	}
	if result.Href == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("href", "result"))
	}
	if result.Fingerprint == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("fingerprint", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/projects/[0-9]+/policy_templates/[0-9a-f]+$"))
	}
	if result.UpdatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.updated_at", *result.UpdatedAt, goa.FormatDateTime))
	}
	if result.UpdatedBy != nil {
		if err2 := result.UpdatedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#policy_template") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#policy_template"}))
		}
	}
	return
}

// Validate runs the validations defined on UserView.
func (result *UserView) Validate() (err error) {
	if result.Email != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.email", *result.Email, goa.FormatEmail))
	}
	return
}

// Validate runs the validations defined on PermissionView.
func (result *PermissionView) Validate() (err error) {

	return
}

// Validate runs the validations defined on ParameterView.
func (result *ParameterView) Validate() (err error) {
	if result.Type != nil {
		if !(*result.Type == "string" || *result.Type == "list" || *result.Type == "number") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.type", *result.Type, []interface{}{"string", "list", "number"}))
		}
	}
	if result.AllowedPattern != nil {
		if err2 := result.AllowedPattern.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// Validate runs the validations defined on RegexpView.
func (result *RegexpView) Validate() (err error) {

	return
}

// Validate runs the validations defined on PublishedTemplateView using the
// "default" view.
func (result *PublishedTemplateView) Validate() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Name == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("name", "result"))
	}
	if result.Href == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("href", "result"))
	}
	if result.Fingerprint == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("fingerprint", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.PolicyTemplateURL != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.policy_template_url", *result.PolicyTemplateURL, goa.FormatURI))
	}
	if result.DocLink != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.doc_link", *result.DocLink, goa.FormatURI))
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/orgs/[0-9]+/published_templates/[0-9a-f]+$"))
	}
	if result.CreatedBy != nil {
		if err2 := result.CreatedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.CreatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.created_at", *result.CreatedAt, goa.FormatDateTime))
	}
	if result.UpdatedBy != nil {
		if err2 := result.UpdatedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.UpdatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.updated_at", *result.UpdatedAt, goa.FormatDateTime))
	}
	if result.HiddenBy != nil {
		if err2 := result.HiddenBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.HiddenAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.hidden_at", *result.HiddenAt, goa.FormatDateTime))
	}
	if result.Severity != nil {
		if !(*result.Severity == "low" || *result.Severity == "medium" || *result.Severity == "high" || *result.Severity == "critical") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.severity", *result.Severity, []interface{}{"low", "medium", "high", "critical"}))
		}
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#published_template") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#published_template"}))
		}
	}
	return
}

// ValidateExtended runs the validations defined on PublishedTemplateView using
// the "extended" view.
func (result *PublishedTemplateView) ValidateExtended() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Name == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("name", "result"))
	}
	if result.Href == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("href", "result"))
	}
	if result.Fingerprint == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("fingerprint", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.PolicyTemplateURL != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.policy_template_url", *result.PolicyTemplateURL, goa.FormatURI))
	}
	if result.DocLink != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.doc_link", *result.DocLink, goa.FormatURI))
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/orgs/[0-9]+/published_templates/[0-9a-f]+$"))
	}
	if result.CreatedBy != nil {
		if err2 := result.CreatedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.CreatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.created_at", *result.CreatedAt, goa.FormatDateTime))
	}
	if result.UpdatedBy != nil {
		if err2 := result.UpdatedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.UpdatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.updated_at", *result.UpdatedAt, goa.FormatDateTime))
	}
	if result.HiddenBy != nil {
		if err2 := result.HiddenBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.HiddenAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.hidden_at", *result.HiddenAt, goa.FormatDateTime))
	}
	for _, v := range result.Parameters {
		if v != nil {
			if err2 := v.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	if result.Severity != nil {
		if !(*result.Severity == "low" || *result.Severity == "medium" || *result.Severity == "high" || *result.Severity == "critical") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.severity", *result.Severity, []interface{}{"low", "medium", "high", "critical"}))
		}
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#published_template") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#published_template"}))
		}
	}
	return
}

// ValidateSource runs the validations defined on PublishedTemplateView using
// the "source" view.
func (result *PublishedTemplateView) ValidateSource() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Name == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("name", "result"))
	}
	if result.Href == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("href", "result"))
	}
	if result.Fingerprint == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("fingerprint", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/orgs/[0-9]+/published_templates/[0-9a-f]+$"))
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#published_template") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#published_template"}))
		}
	}
	return
}

// ValidateLink runs the validations defined on PublishedTemplateView using the
// "link" view.
func (result *PublishedTemplateView) ValidateLink() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Name == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("name", "result"))
	}
	if result.Href == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("href", "result"))
	}
	if result.Fingerprint == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("fingerprint", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/orgs/[0-9]+/published_templates/[0-9a-f]+$"))
	}
	if result.UpdatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.updated_at", *result.UpdatedAt, goa.FormatDateTime))
	}
	if result.UpdatedBy != nil {
		if err2 := result.UpdatedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#published_template") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#published_template"}))
		}
	}
	return
}

// Validate runs the validations defined on ConfigurationOptionView.
func (result *ConfigurationOptionView) Validate() (err error) {
	if result.Type != nil {
		if !(*result.Type == "string" || *result.Type == "number" || *result.Type == "list") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.type", *result.Type, []interface{}{"string", "number", "list"}))
		}
	}
	return
}

// Validate runs the validations defined on IncidentListView using the
// "default" view.
func (result *IncidentListView) Validate() (err error) {
	if result.Etag == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("etag", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.NotModified != nil {
		if !(*result.NotModified == "true" || *result.NotModified == "false") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.not_modified", *result.NotModified, []interface{}{"true", "false"}))
		}
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#incident_list") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#incident_list"}))
		}
	}
	if result.Items != nil {
		if err2 := result.Items.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// ValidateExtended runs the validations defined on IncidentListView using the
// "extended" view.
func (result *IncidentListView) ValidateExtended() (err error) {
	if result.Etag == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("etag", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.NotModified != nil {
		if !(*result.NotModified == "true" || *result.NotModified == "false") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.not_modified", *result.NotModified, []interface{}{"true", "false"}))
		}
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#incident_list") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#incident_list"}))
		}
	}
	if result.Items != nil {
		if err2 := result.Items.ValidateExtended(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// Validate runs the validations defined on IncidentCollectionView using the
// "default" view.
func (result IncidentCollectionView) Validate() (err error) {
	for _, item := range result {
		if err2 := item.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// ValidateExtended runs the validations defined on IncidentCollectionView
// using the "extended" view.
func (result IncidentCollectionView) ValidateExtended() (err error) {
	for _, item := range result {
		if err2 := item.ValidateExtended(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// ValidateSource runs the validations defined on IncidentCollectionView using
// the "source" view.
func (result IncidentCollectionView) ValidateSource() (err error) {
	for _, item := range result {
		if err2 := item.ValidateSource(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// Validate runs the validations defined on EscalationsView using the "default"
// view.
func (result *EscalationsView) Validate() (err error) {
	if result.Status == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("status", "result"))
	}
	if result.Status != nil {
		if !(*result.Status == "queued" || *result.Status == "aborted" || *result.Status == "pending" || *result.Status == "running" || *result.Status == "completed" || *result.Status == "failed" || *result.Status == "denied") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.status", *result.Status, []interface{}{"queued", "aborted", "pending", "running", "completed", "failed", "denied"}))
		}
	}
	for _, e := range result.Escalations {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	if result.StartedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.started_at", *result.StartedAt, goa.FormatDateTime))
	}
	if result.FinishedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.finished_at", *result.FinishedAt, goa.FormatDateTime))
	}
	return
}

// Validate runs the validations defined on EscalationView using the "default"
// view.
func (result *EscalationView) Validate() (err error) {
	if result.Status == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("status", "result"))
	}
	if result.Name == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("name", "result"))
	}
	if result.Actions == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("actions", "result"))
	}
	if result.Status != nil {
		if !(*result.Status == "queued" || *result.Status == "aborted" || *result.Status == "pending" || *result.Status == "running" || *result.Status == "completed" || *result.Status == "failed" || *result.Status == "denied") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.status", *result.Status, []interface{}{"queued", "aborted", "pending", "running", "completed", "failed", "denied"}))
		}
	}
	for _, e := range result.Actions {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// Validate runs the validations defined on EscalationActionView using the
// "default" view.
func (result *EscalationActionView) Validate() (err error) {
	if result.Type == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("type", "result"))
	}
	if result.Status == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("status", "result"))
	}
	if result.Type != nil {
		if !(*result.Type == "email" || *result.Type == "cloud_workflow" || *result.Type == "resolve_incident" || *result.Type == "request_approval") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.type", *result.Type, []interface{}{"email", "cloud_workflow", "resolve_incident", "request_approval"}))
		}
	}
	if result.Status != nil {
		if !(*result.Status == "queued" || *result.Status == "pending" || *result.Status == "running" || *result.Status == "completed" || *result.Status == "skipped" || *result.Status == "failed" || *result.Status == "approved" || *result.Status == "denied") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.status", *result.Status, []interface{}{"queued", "pending", "running", "completed", "skipped", "failed", "approved", "denied"}))
		}
	}
	if result.StartedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.started_at", *result.StartedAt, goa.FormatDateTime))
	}
	if result.FinishedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.finished_at", *result.FinishedAt, goa.FormatDateTime))
	}
	if result.ApprovalRequest != nil {
		if err2 := result.ApprovalRequest.ValidateExtended(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}

// Validate runs the validations defined on ApprovalRequestView using the
// "default" view.
func (result *ApprovalRequestView) Validate() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Href == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("href", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.Subject == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("subject", "result"))
	}
	if result.ProjectID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("project_id", "result"))
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/projects/[0-9]+/approval_requests/[0-9a-f]+$"))
	}
	if result.Subject != nil {
		if err2 := result.Subject.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.CreatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.created_at", *result.CreatedAt, goa.FormatDateTime))
	}
	if result.UpdatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.updated_at", *result.UpdatedAt, goa.FormatDateTime))
	}
	if result.Status != nil {
		if !(*result.Status == "pending" || *result.Status == "approved" || *result.Status == "denied") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.status", *result.Status, []interface{}{"pending", "approved", "denied"}))
		}
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#approval_request") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#approval_request"}))
		}
	}
	return
}

// ValidateExtended runs the validations defined on ApprovalRequestView using
// the "extended" view.
func (result *ApprovalRequestView) ValidateExtended() (err error) {
	if result.ID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("id", "result"))
	}
	if result.Href == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("href", "result"))
	}
	if result.Kind == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("kind", "result"))
	}
	if result.Subject == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("subject", "result"))
	}
	if result.ProjectID == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("project_id", "result"))
	}
	if result.Href != nil {
		err = goa.MergeErrors(err, goa.ValidatePattern("result.href", *result.Href, "^/api/governance/projects/[0-9]+/approval_requests/[0-9a-f]+$"))
	}
	if result.Subject != nil {
		if err2 := result.Subject.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.CreatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.created_at", *result.CreatedAt, goa.FormatDateTime))
	}
	if result.UpdatedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.updated_at", *result.UpdatedAt, goa.FormatDateTime))
	}
	if result.Status != nil {
		if !(*result.Status == "pending" || *result.Status == "approved" || *result.Status == "denied") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.status", *result.Status, []interface{}{"pending", "approved", "denied"}))
		}
	}
	for _, v := range result.Parameters {
		if v != nil {
			if err2 := v.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	for _, e := range result.Options {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	if result.ApprovedBy != nil {
		if err2 := result.ApprovedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.ApprovedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.approved_at", *result.ApprovedAt, goa.FormatDateTime))
	}
	if result.DeniedBy != nil {
		if err2 := result.DeniedBy.Validate(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	if result.DeniedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.denied_at", *result.DeniedAt, goa.FormatDateTime))
	}
	if result.Kind != nil {
		if !(*result.Kind == "gov#approval_request") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.kind", *result.Kind, []interface{}{"gov#approval_request"}))
		}
	}
	return
}

// Validate runs the validations defined on ApprovalSubject2.
func (result *ApprovalSubject2) Validate() (err error) {

	return
}

// Validate runs the validations defined on ResolutionsView using the "default"
// view.
func (result *ResolutionsView) Validate() (err error) {
	if result.Status == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("status", "result"))
	}
	if result.Status != nil {
		if !(*result.Status == "queued" || *result.Status == "aborted" || *result.Status == "pending" || *result.Status == "running" || *result.Status == "completed" || *result.Status == "failed" || *result.Status == "denied") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.status", *result.Status, []interface{}{"queued", "aborted", "pending", "running", "completed", "failed", "denied"}))
		}
	}
	for _, e := range result.Resolutions {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	if result.StartedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.started_at", *result.StartedAt, goa.FormatDateTime))
	}
	if result.FinishedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.finished_at", *result.FinishedAt, goa.FormatDateTime))
	}
	return
}

// Validate runs the validations defined on ResolutionView using the "default"
// view.
func (result *ResolutionView) Validate() (err error) {
	if result.Status == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("status", "result"))
	}
	if result.Name == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("name", "result"))
	}
	if result.Actions == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("actions", "result"))
	}
	if result.Status != nil {
		if !(*result.Status == "queued" || *result.Status == "aborted" || *result.Status == "pending" || *result.Status == "running" || *result.Status == "completed" || *result.Status == "failed" || *result.Status == "denied") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.status", *result.Status, []interface{}{"queued", "aborted", "pending", "running", "completed", "failed", "denied"}))
		}
	}
	for _, e := range result.Actions {
		if e != nil {
			if err2 := e.Validate(); err2 != nil {
				err = goa.MergeErrors(err, err2)
			}
		}
	}
	return
}

// Validate runs the validations defined on ResolutionActionView using the
// "default" view.
func (result *ResolutionActionView) Validate() (err error) {
	if result.Type == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("type", "result"))
	}
	if result.Status == nil {
		err = goa.MergeErrors(err, goa.MissingFieldError("status", "result"))
	}
	if result.Type != nil {
		if !(*result.Type == "email" || *result.Type == "cloud_workflow" || *result.Type == "request_approval") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.type", *result.Type, []interface{}{"email", "cloud_workflow", "request_approval"}))
		}
	}
	if result.Status != nil {
		if !(*result.Status == "queued" || *result.Status == "pending" || *result.Status == "running" || *result.Status == "completed" || *result.Status == "skipped" || *result.Status == "failed" || *result.Status == "approved" || *result.Status == "denied") {
			err = goa.MergeErrors(err, goa.InvalidEnumValueError("result.status", *result.Status, []interface{}{"queued", "pending", "running", "completed", "skipped", "failed", "approved", "denied"}))
		}
	}
	if result.StartedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.started_at", *result.StartedAt, goa.FormatDateTime))
	}
	if result.FinishedAt != nil {
		err = goa.MergeErrors(err, goa.ValidateFormat("result.finished_at", *result.FinishedAt, goa.FormatDateTime))
	}
	if result.ApprovalRequest != nil {
		if err2 := result.ApprovalRequest.ValidateExtended(); err2 != nil {
			err = goa.MergeErrors(err, err2)
		}
	}
	return
}
